import { mkdirSync, writeFileSync, existsSync, statSync } from 'node:fs'
import { join } from 'node:path'
import { createHash } from 'node:crypto'

/*
 * Downloads the webfonts and writes a local @font-face stylesheet, keeping two
 * third-party origins off the critical path. Output is committed so the build
 * does not depend on the network. Re-run to refresh.
 */

const ROOT = join(import.meta.dirname, '..')
const FONT_DIR = join(ROOT, 'public', 'fonts')
const CSS_OUT = join(ROOT, 'src', 'css', 'fonts.css')

const SPEC =
  'family=Space+Grotesk:wght@500;700&family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400&display=swap'

// A modern browser UA is required, or Google serves legacy TTF instead of woff2.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36'

// Latin only. latin-ext adds ~85KB for Inter alone and the site has no content
// that needs it.
const KEEP_SUBSETS = new Set(['latin'])

const css = await (
  await fetch(`https://fonts.googleapis.com/css2?${SPEC}`, { headers: { 'User-Agent': UA } })
).text()

mkdirSync(FONT_DIR, { recursive: true })

// Google emits a `/* subset */` comment before each @font-face block.
const blocks = css
  .split(/\/\*\s*([\w-]+)\s*\*\//)
  .slice(1)
  .reduce((acc, part, i, arr) => {
    if (i % 2 === 0) acc.push({ subset: part, body: arr[i + 1] ?? '' })
    return acc
  }, [])

// These are variable fonts: every requested weight returns the same file, so
// faces are deduplicated by content hash and emitted once with a weight range.
const byHash = new Map()

for (const { subset, body } of blocks) {
  if (!KEEP_SUBSETS.has(subset)) continue

  const family = body.match(/font-family:\s*'([^']+)'/)?.[1]
  const weight = Number(body.match(/font-weight:\s*(\d+)/)?.[1])
  const style = body.match(/font-style:\s*(\w+)/)?.[1] ?? 'normal'
  const url = body.match(/url\((https:[^)]+\.woff2)\)/)?.[1]
  const range = body.match(/unicode-range:\s*([^;]+);/)?.[1]
  if (!family || !url) continue

  const buf = Buffer.from(await (await fetch(url)).arrayBuffer())
  const hash = createHash('sha1').update(buf).digest('hex').slice(0, 8)

  const existing = byHash.get(hash)
  if (existing) {
    existing.weights.push(weight)
    continue
  }
  byHash.set(hash, { family, style, range, buf, weights: [weight], hash })
}

const out = []
let bytes = 0

for (const face of byHash.values()) {
  const slug = `${face.family.toLowerCase().replace(/\s+/g, '-')}-${face.hash}.woff2`
  writeFileSync(join(FONT_DIR, slug), face.buf)
  bytes += face.buf.length

  const lo = Math.min(...face.weights)
  const hi = Math.max(...face.weights)

  out.push({
    slug,
    family: face.family,
    css:
      `@font-face {\n` +
      `  font-family: '${face.family}';\n` +
      `  font-style: ${face.style};\n` +
      `  font-weight: ${lo === hi ? lo : `${lo} ${hi}`};\n` +
      `  font-display: swap;\n` +
      `  src: url('/fonts/${slug}') format('woff2');\n` +
      (face.range ? `  unicode-range: ${face.range};\n` : '') +
      `}`,
  })
}

writeFileSync(
  CSS_OUT,
  `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.\n` +
    `   Re-run that script to refresh. Files live in public/fonts/. */\n\n` +
    `@layer tokens {\n` +
    out.map((b) => b.css.replace(/^/gm, '  ')).join('\n\n') +
    `\n}\n`
)

console.log(`fonts: ${out.length} unique face(s), ${(bytes / 1024).toFixed(1)}KB total`)
out.forEach((f) => console.log(`  ${f.slug}`))
console.log('\nPreload these in index.html <head>:')
out.forEach((f) =>
  console.log(`  <link rel="preload" href="/fonts/${f.slug}" as="font" type="font/woff2" crossorigin />`)
)
